# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1068fc9f4041e9c79ce4327f0b569886290f31eece934a2a45a5097d3260f5af539b7e8d2b1c52daa474b9bf6fe68f2c14e909a765d1a554952148a6dbab4223

test:
  secret_key_base: 071b160b1fcfd7105b5adf1c99905b193fe0f7395a1b31fbb95ea8e843e99731824ec3f20bac4418501255dfa16e64e5b996b9b31e78eb923b1c528006b4f346

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
